version: 2

models:
  - name: mart_customer_data
    description: "customer data by nations and regions with various dimensions"
    columns:
      - name: nation
        description: "The nation of the customer"
      - name: year
        description: "The year of the transaction"
      - name: month
        description: "The month of the transaction"
      - name: day
        description: "The day of the transaction"
      - name: i_category
        description: "The category of the item"
      - name: i_class
        description: "The class of the item"
      - name: i_brand
        description: "The brand of the item"
      - name: total_quantity
        description: "The total quantity of items ordered"
        tests:
          - not_null
      - name: total_net_paid
        description: "The total net amount paid"
        tests:
          - not_null
      - name: total_net_paid_inc_tax
        description: "The total net amount paid including tax"
      - name: total_net_paid_inc_ship
        description: "The total net amount paid including shipping"
      - name: total_net_paid_inc_ship_tax
        description: "The total net amount paid including shipping and tax"
      - name: city
        description: "The city of the customer"
      - name: state
        description: "The state of the customer"
      - name: country
        description: "The country of the customer"
      - name: max_revenue
        description: "The maximum revenue from the customer"
        tests:
          - not_null


  - name: mart_order_revenue
    description: "order revenue for analytical purposes by various dimensions"
    columns:
      - name: city
        description: "The city where the order was placed."
      - name: state
        description: "The state where the order was placed."
      - name: country
        description: "The country where the order was placed."
      - name: max_revenue
        description: "The maximum revenue generated by an item in the order."
      - name: nation
        description: "The nation associated with the order, derived from the country."
      - name: year
        description: "The year when the order was placed."
      - name: month
        description: "The month when the order was placed."
      - name: day
        description: "The day when the order was placed."
      - name: i_category
        description: "The category of items in the order."
      - name: i_class
        description: "The class of items in the order."
      - name: i_brand
        description: "The brand of items in the order."
      - name: total_quantity
        description: "The total quantity of items in the order."
        tests:
          - not_null
          - greater_than:
              compare_to: 0
      - name: total_net_paid
        description: "The total net amount paid for the order."
        tests:
          - not_null
          - greater_than:
              compare_to: 0
      - name: total_net_paid_inc_tax
        description: "The total net amount paid for the order including tax."
        tests:
          - not_null
          - greater_than: 
              compare_to: 0
      - name: total_net_paid_inc_ship
        description: "The total net amount paid for the order including shipping costs."
        tests:
          - not_null
          - greater_than: 
              compare_to: 0
      - name: total_net_paid_inc_ship_tax
        description: "The total net amount paid for the order including shipping costs and tax."
        tests:
          - not_null
          - greater_than: 
              compare_to: 0


  - name: mart_sold_items_by_region_with_date
    description: "sold items by region with date with various dimensions"
    columns:
      - name: region
        description: "The region where the items were sold."
      - name: customer_id
        description: "The ID of the customer who made the purchase."
      - name: lineitems_bought
        description: "The number of line items bought by the customer."
      - name: max_revenue_per_customer
        description: "The maximum revenue generated from a customer."

