version: 2

models:
  - name: int_avg_revenue_per_customer_order
    description: "average revenue per customer order"
    columns:
      - name: customer_sk
        description: "Unique identifier for each customer."
      - name: avg_revenue_per_order
        description: "The average revenue generated per order by a customer."
    tests:
      - unique:
          column_name: customer_sk
      - not_null:
          column_name: customer_sk
      - not_null:
          column_name: avg_revenue_per_order


  - name: int_item_sold_by_month
    description: "This model aggregates the total quantity of items sold by month, including the year, month, item ID, and item description."
    columns:
      - name: year
        description: "The year when the item was sold."
        tests:
          - not_null
      - name: month_seq
        description: "The sequence number of the month when the item was sold."
        tests:
          - not_null
      - name: item_id
        description: "The unique identifier for the item."
        tests:
          - not_null
          - unique
      - name: item_desc
        description: "The description of the item."
      - name: total_quantity_sold
        description: "The total quantity of the item sold in the given month and year."
        tests:
          - not_null


  - name: int_lineitem_revenue
    description: "max revenue per customer by region"
    columns:
      - name: city
        description: "The city of the customer."
      - name: state
        description: "The state of the customer."
      - name: country
        description: "The country of the customer."
      - name: max_revenue
        description: "The maximum revenue generated by a customer in the respective city, state, and country."
        tests:
          - not_null
          - unique


  - name: int_lineitem_sold_per_customer
    description: "lineitems bought by customer"
    columns:
      - name: customer_id
        description: "Unique identifier for the customer."
      - name: ws_order_number
        description: "Order number associated with the web sale."
      - name: item_id
        description: "Identifier for the item sold."
      - name: item_desc
        description: "Description of the item."
      - name: brand
        description: "Brand of the item."
      - name: class
        description: "Class category of the item."
      - name: category
        description: "Category of the item."
      - name: date
        description: "Date when the item was sold."
      - name: ws_quantity
        description: "Quantity of the item sold."
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
      - name: ws_wholesale_cost
        description: "Wholesale cost of the item."
      - name: ws_sales_price
        description: "Sales price of the item."


  - name: int_ordering_habits_per_nation
    description: "ordering habits by nation"
    columns:
      - name: nation
        description: "The birth country of the customer."
      - name: year
        description: "The year when the sale was made."
      - name: month
        description: "The month when the sale was made."
      - name: day
        description: "The day of the month when the sale was made."
      - name: i_category
        description: "The category of the item sold."
      - name: i_class
        description: "The class of the item sold."
      - name: i_brand
        description: "The brand of the item sold."
      - name: total_quantity
        description: "The total quantity of items sold."
        tests:
          - not_null
          - greater_than:
              compare_to: 0
      - name: total_net_paid
        description: "The total net amount paid by the customers."
        tests:
          - not_null
          - greater_than:
              compare_to: 0
      - name: total_net_paid_inc_tax
        description: "The total net amount paid by the customers including tax."
        tests:
          - not_null
          - greater_than:
              compare_to: 0
      - name: total_net_paid_inc_ship
        description: "The total net amount paid by the customers including shipping."
        tests:
          - not_null
          - greater_than:
              compare_to: 0
      - name: total_net_paid_inc_ship_tax
        description: "The total net amount paid by the customers including shipping and tax."
        tests:
          - not_null
          - greater_than:
              compare_to: 0

